# Generated by Django 3.2.7 on 2021-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=150)),
                ('player_email', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('game', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
